name: 'Ariadne AI Agent'
description: 'Like Ariadne''s thread through the labyrinth - navigate massive codebases with LLM-powered agents for code analysis, PR reviews, and automated tasks'
author: 'richinex'

branding:
  icon: 'compass'
  color: 'purple'

inputs:
  task:
    description: 'The task or prompt for the agent to execute'
    required: true

  command:
    description: 'Command to run: react-run (single agent) or rlm (reasoning agent)'
    required: false
    default: 'react-run'

  provider:
    description: 'LLM provider: openai, anthropic, deepseek, or gemini'
    required: true

  api_key:
    description: 'API key for the LLM provider. MUST use GitHub secrets (e.g., secrets.OPENAI_API_KEY). Never commit API keys to repository.'
    required: true

  max_iter:
    description: 'Maximum number of reasoning iterations'
    required: false
    default: '25'

  verbose:
    description: 'Enable verbose logging'
    required: false
    default: 'false'

  depth:
    description: 'Search depth (only used with command: rlm)'
    required: false
    default: '3'

  timeout:
    description: 'Timeout in seconds (only used with command: rlm)'
    required: false
    default: '120'

  subagent_provider:
    description: 'LLM provider for sub-agents in RLM mode (cost optimization): openai, anthropic, deepseek, gemini. Example: provider=openai subagent_provider=deepseek uses gpt-5.2 for root, deepseek-chat for children.'
    required: false
    default: ''

  subagent_api_key:
    description: 'API key for subagent provider (required if subagent_provider is different from main provider). Use GitHub secrets.'
    required: false
    default: ''

outputs:
  result:
    description: 'Output from the ariadne agent'

  exit-code:
    description: 'Exit code from ariadne execution (0 = success)'

runs:
  using: 'docker'
  image: 'Dockerfile'
